### PR TITLE
Fix range order

### LINKED ISSUE #5: Ranges are being labelled wrong
The step i.e. increment is optional but in the middle ([docs](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Conditional_and_Iterator_Functions#For_loop)). The end is currently parsed as the increment when you have all 3 expressions. 

```scad
 for(variable = [start : increment : end])
 for(variable = [start : end])
```

In addition to fixing the parsing, can we move the position in the datatype to avoid confusion?

```haskell
data Range a = Range a (Maybe a) a
```

### PR DESCRIPTION
**Pull request by BrechtSerckx**
Option step is in the middle
Closes https://github.com/bgamari/language-openscad/issues/5

Please review after #13

### CODE REVIEW

**Comment by bgamari** [comment]
Apologies, I rebase-merged #13 and apparently GitHub is unable to manually resolve the trivial conflicts that result. Would you mind doing so?

Again, sorry for the inconvenience.

**Comment by BrechtSerckx** [comment]
Of course, not a problem! It might be for later this weekend though.

**Comment by BrechtSerckx** [comment]
@bgamari I know you're probably very busy, but FYI the conflicts have been resolved.

**Comment by bgamari** [comment]
Thanks @BrechtSerckx !

Out of curiosity, would you be interested in acting as a co-maintainer of this package?

**Comment by BrechtSerckx** [comment]
> Thanks @BrechtSerckx !
> 
> Out of curiosity, would you be interested in acting as a co-maintainer of this package?

I would love to help out!
I must say I don't have any experience with being a package maintainer, but I can of course look at issues and PRs.

**Comment by bgamari** [comment]
I have granted you commit rights to the repository. If you have a Hackage account let me know your user name and I can add you to the maintainers group so that you can make releases.

**Comment by bgamari** [comment]
Also, in general feel free to make releases when you feel is necessary. Alternatively, if you would prefer not to do so yourself let me know and I can push to Hackage.

**Comment by BrechtSerckx** [comment]
Thanks! 
My Hackage username is [BrechtSerckx](https://hackage.haskell.org/user/BrechtSerckx).
(I'm not in the Package Uploaders group yet as I don't have a package, but I believe that does not matter)

As for the release, I'd think now would be a good time for version 0.1.8. I'll look into that.

**Comment by bgamari** [comment]
You should now have upload rights.

**Pull request merged**
